FROM python:3.10.11 as base

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_NO_WARN_SCRIPT_LOCATION=0 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_DISABLE_ROOT_WARNING=ignore

COPY llm/requirements.txt .

RUN pip install -r requirements.txt 

WORKDIR /home


FROM base as llm

EXPOSE 8080 443

ARG LLM_API_KEY
ARG LLM_HTTP_LISTEN_PORT

ENV LLM_API_KEY=${LLM_API_KEY}
ENV LLM_HTTP_LISTEN_PORT=${LLM_HTTP_LISTEN_PORT}

# COPY llm/chatbot .

ENTRYPOINT ["python","/home/chatbot/app.py"]