{
 "title": "test",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ISIS Neighbor state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mdt_grpc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-isis-oper:isis-oper-data/isis-instance/isis-neighbor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status_code\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mdt_grpc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory_pool\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_used\")\n  |> filter(fn: (r) => r[\"device\"] == \"cat8000v-0\" or r[\"device\"] == \"cat8000v-1\")\n  |> filter(fn: (r) => r[\"ip\"] == \"10.10.20.176\" or r[\"ip\"] == \"10.10.20.175\")\n  |> filter(fn: (r) => r[\"name\"] == \"Processor\" or r[\"name\"] == \"lsmpi_io\" or r[\"name\"] == \"reserve Processor\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Interface Traffic tx/rx kbps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mdt_grpc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_statistics\")\n  |> filter(fn: (r) => r[\"device\"] == \"cat8000v-1\" or r[\"device\"] == \"cat8000v-0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tx-kbps\" or r[\"_field\"] == \"rx-kbps\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Interface Oper status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mdt_grpc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_statistics\")\n  |> filter(fn: (r) => r[\"device\"] == \"cat8000v-1\" or r[\"device\"] == \"cat8000v-0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"operational_status\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"mdt_grpc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"cat8000v-1\" or r[\"source\"] == \"cat8000v-0\")\n  |> filter(fn: (r) => r[\"subscription\"] == \"1010\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five_seconds\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"mdt_grpc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_statistics\")\n  |> filter(fn: (r) => r[\"device\"] == \"cat8000v-1\" or r[\"device\"] == \"cat8000v-0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"out_errors\" or r[\"_field\"] == \"in_errors\" or r[\"_field\"] == \"in-discards\" or r[\"_field\"] == \"in-crc-errors\" or r[\"_field\"] == \"in-errors-64\" or r[\"_field\"] == \"out-discards\" or r[\"_field\"] == \"out-broadcast-pkts\" or r[\"_field\"] == \"out-multicast-pkts\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Interface flaps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"mdt_grpc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_statistics\")\n  |> filter(fn: (r) => r[\"device\"] == \"cat8000v-1\" or r[\"device\"] == \"cat8000v-0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"num-flaps\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}