# syntax=docker/dockerfile:1
FROM python:alpine3.16 AS base
COPY ./cml/requirements.txt .
RUN apk add \
    gcc \
    bash \
    musl-dev \
    libssh-dev \
    linux-headers \
    openssh-client \
    && pip install --upgrade pip \
    && pip install -r requirements.txt \
    && ansible-galaxy collection install cisco.cml
WORKDIR /home


FROM base as cml

ARG CML_LAB
ARG CML_HOST
ARG CML_LAB_FILE
ARG CML_USERNAME
ARG CML_PASSWORD
ARG CML_VERIFY_CERT

ENV CML_LAB=${CML_LAB}
ENV CML_HOST=${CML_HOST}
ENV CML_LAB_FILE=${CML_LAB_FILE}
ENV CML_USERNAME=${CML_USERNAME}
ENV CML_PASSWORD=${CML_PASSWORD}
ENV CML_VERIFY_CERT=${CML_VERIFY_CERT}

COPY cml/ansible/ /home/
